apiVersion: v1
kind: Secret
metadata:
  name: haproxy-config
  namespace: haproxy-operator
type: Opaque
stringData:
  haproxy.cfg: |
    global
      daemon
      default-path config
      chroot /var/lib/haproxy
      user haproxy
      group haproxy
      maxconn 10000
      pidfile /var/run/haproxy.pid
      stats socket /var/run/haproxy-runtime-api.sock level admin expose-fd listeners

    defaults unnamed_defaults_1
      timeout http-request 5000
      timeout connect 5000
      timeout client 50000
      timeout queue 5000
      timeout server 50000
      timeout tunnel 3600000
      timeout http-keep-alive 60000

    frontend http
      mode http
      bind *:80
      use_backend backend_cluster

    frontend stats
      mode http
      bind *:8404
      no log
      stats uri /
      stats enable

    backend backend_cluster
      mode http
      balance roundrobin
      option httpchk
      http-check send meth GET uri /
      default-server inter 10s rise 2 fall 3
      server backend-1 172.20.0.11:80 check
      server backend-2 172.20.0.12:80 check
      server backend-3 172.20.0.13:80 check
