# HelmRelease for deploying the haproxy-operator.
# Adjust values per environment (latest vs stable).
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-operator
  namespace: haproxy-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: haproxy-operator
      version: ">=0.0.0-0"  # latest env; use ">=1.0.0" for stable
      sourceRef:
        kind: HelmRepository
        name: haproxy-operator
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    dataplane:
      url: "https://haproxy-dev.tlu.bcit.ca:5555/v3"  # CHANGEME
    spire:
      enabled: true
    vault:
      enabled: true
