# OCI HelmRepository for the haproxy-operator chart published to GHCR.
---
apiVersion: source.toolkit.fluxcd.io/v2
kind: HelmRepository
metadata:
  name: haproxy-operator
  namespace: haproxy-operator
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/bcit-tlu/haproxy-operator/charts
